<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyName>terminalfs</AssemblyName>
    <RootNamespace>TerminalFs</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NineP.Server" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../TerminalFs.Core/TerminalFs.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="TerminalFs.Tests" />
  </ItemGroup>

</Project>
